package com.sarah.mystockwatcher;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.sarah.mystockwatcher.Stock;
import com.sarah.mystockwatcher.UserSetting;

import com.sarah.mystockwatcher.StockDao;
import com.sarah.mystockwatcher.UserSettingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stockDaoConfig;
    private final DaoConfig userSettingDaoConfig;

    private final StockDao stockDao;
    private final UserSettingDao userSettingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        userSettingDaoConfig = daoConfigMap.get(UserSettingDao.class).clone();
        userSettingDaoConfig.initIdentityScope(type);

        stockDao = new StockDao(stockDaoConfig, this);
        userSettingDao = new UserSettingDao(userSettingDaoConfig, this);

        registerDao(Stock.class, stockDao);
        registerDao(UserSetting.class, userSettingDao);
    }
    
    public void clear() {
        stockDaoConfig.getIdentityScope().clear();
        userSettingDaoConfig.getIdentityScope().clear();
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public UserSettingDao getUserSettingDao() {
        return userSettingDao;
    }

}
