package com.sarah.mystockwatcher;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STOCK".
 */
public class Stock {

    private Long id;
    /** Not-null value. */
    private String symbol;
    /** Not-null value. */
    private String name;
    private Double eps;
    private Double yearHigh;
    private Double yearLow;
    private Double open;
    private String percentChange;
    private Long exDividendDate;
    private Long dividendPayDate;
    private Double dividendAverage;

    public Stock() {
    }

    public Stock(Long id) {
        this.id = id;
    }

    public Stock(Long id, String symbol, String name, Double eps, Double yearHigh, Double yearLow, Double open, String percentChange, Long exDividendDate, Long dividendPayDate, Double dividendAverage) {
        this.id = id;
        this.symbol = symbol;
        this.name = name;
        this.eps = eps;
        this.yearHigh = yearHigh;
        this.yearLow = yearLow;
        this.open = open;
        this.percentChange = percentChange;
        this.exDividendDate = exDividendDate;
        this.dividendPayDate = dividendPayDate;
        this.dividendAverage = dividendAverage;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getSymbol() {
        return symbol;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Double getEps() {
        return eps;
    }

    public void setEps(Double eps) {
        this.eps = eps;
    }

    public Double getYearHigh() {
        return yearHigh;
    }

    public void setYearHigh(Double yearHigh) {
        this.yearHigh = yearHigh;
    }

    public Double getYearLow() {
        return yearLow;
    }

    public void setYearLow(Double yearLow) {
        this.yearLow = yearLow;
    }

    public Double getOpen() {
        return open;
    }

    public void setOpen(Double open) {
        this.open = open;
    }

    public String getPercentChange() {
        return percentChange;
    }

    public void setPercentChange(String percentChange) {
        this.percentChange = percentChange;
    }

    public Long getExDividendDate() {
        return exDividendDate;
    }

    public void setExDividendDate(Long exDividendDate) {
        this.exDividendDate = exDividendDate;
    }

    public Long getDividendPayDate() {
        return dividendPayDate;
    }

    public void setDividendPayDate(Long dividendPayDate) {
        this.dividendPayDate = dividendPayDate;
    }

    public Double getDividendAverage() {
        return dividendAverage;
    }

    public void setDividendAverage(Double dividendAverage) {
        this.dividendAverage = dividendAverage;
    }

}
